export default {
  SC_CLIENT_ID: '',//'TnLKn5dpBpgxI51x2I89h6KOypTECZPF',
  SC_CLIENT_SECRET:'',
  SC_OAUTH_REDIRECT_URI: '',
  GOOG_ANALYTICS_ID : '',
  BUGSNAG_API_KEY: '',
  ADMOB_BANNER_ID: '',
  ADMOB_REWARDED_ID: '',
  OVERRIDE_STREAM_TOKEN: false,
};