export const actionTypes = {
  CHANGE_PLAYBACK_MODE: 'CHANGE_PLAYBACK_MODE',
  TOGGLE_PLAYER_MUTE: 'TOGGLE_PLAYER_MUTE',
  TOGGLE_PLAYER_PAN: 'TOGGLE_PLAYER_PAN',
  SET_SONGPICKER_SEARCH: 'SET_SONGPICKER_SEARCH',
  GET_SONGPICKER_SEARCH: 'GET_SONGPICKER_SEARCH',
  CLEAR_SONGPICKER_SEARCH: 'GET_SONGPICKER_SEARCH',
  GET_PLAYLIST : 'GET_PLAYLIST',
  SET_PLAYLIST : 'SET_PLAYLIST',
  CLEAR_PLAYLIST: 'CLEAR_PLAYLIST',
  ADD_PLAYLIST_ITEM : 'ADD_PLAYLIST_ITEM',
  REMOVE_PLAYLIST_ITEM : 'REMOVE_PLAYLIST_ITEM'
}
//TODO: move out on his own appConstant file
export const playbackModeTypes = {
  SPLIT : 'S',
  LEFT : 'L',
  RIGHT : 'R'
}
